#!/bin/bash


CUDA_VISIBLE_DEVICES=0,1 python cli_gt.py \
        --do_train \
        --output_dir ./out/webnlg/bart_few0005/model \
        --train_file ./data/webnlg/train_0005 \
        --train_file_unlabel ./data/webnlg/unlabel \
        --predict_file ./data/webnlg/val \
        --substitution_file ./data/counterfitted_neighbors.json \
        --model_path ./bart_model \
        --tokenizer_path ./bart_model \
        --curriculum [2,4,7] \
        --train_batch_size 32 \
        --train_batch_size_unlabel 32 \
        --predict_batch_size 64 \
        --predict_batch_size_unlabel 64 \
        --max_input_length 256 \
        --max_output_length 128 \
        --append_another_bos \
        --learning_rate 3e-5 \
        --num_train_epochs 20 \
        --num_train_epochs_unlabel 1 \
        --warmup_steps 4 \
        --warmup_steps_unlabel 400 \
        --eval_period 4 \
        --num_beams 5 \
        --struct_noise 0.4 \
        --semantic_noise 0.4 \
        --seed 42 

CUDA_VISIBLE_DEVICES=0,1 python cli_gt.py \
        --do_train \
        --output_dir ./out/webnlg/bart_few001/model \
        --train_file ./data/webnlg/train_001 \
        --train_file_unlabel ./data/webnlg/unlabel \
        --predict_file ./data/webnlg/val \
        --substitution_file ./data/counterfitted_neighbors.json \
        --model_path ./bart_model \
        --tokenizer_path ./bart_model \
        --curriculum [2,4,7] \
        --train_batch_size 32 \
        --train_batch_size_unlabel 32 \
        --predict_batch_size 64 \
        --predict_batch_size_unlabel 64 \
        --max_input_length 256 \
        --max_output_length 128 \
        --append_another_bos \
        --learning_rate 3e-5 \
        --num_train_epochs 20 \
        --num_train_epochs_unlabel 1 \
        --warmup_steps 8 \
        --warmup_steps_unlabel 400 \
        --eval_period 8 \
        --num_beams 5 \
        --struct_noise 0.4 \
        --semantic_noise 0.4 \
        --seed 42

CUDA_VISIBLE_DEVICES=0,1 python cli_gt.py \
        --do_train \
        --output_dir ./out/webnlg/bart_few005/model \
        --train_file ./data/webnlg/train_005 \
        --train_file_unlabel ./data/webnlg/unlabel \
        --predict_file ./data/webnlg/val \
        --substitution_file ./data/counterfitted_neighbors.json \
        --model_path ./bart_model \
        --tokenizer_path ./bart_model \
        --curriculum [2,4,7] \
        --train_batch_size 32 \
        --train_batch_size_unlabel 32 \
        --predict_batch_size 64 \
        --predict_batch_size_unlabel 64 \
        --max_input_length 256 \
        --max_output_length 128 \
        --append_another_bos \
        --learning_rate 3e-5 \
        --num_train_epochs 20 \
        --num_train_epochs_unlabel 1 \
        --warmup_steps 40 \
        --warmup_steps_unlabel 400 \
        --eval_period 40 \
        --num_beams 5 \
        --struct_noise 0.4 \
        --semantic_noise 0.4 \
        --seed 42

CUDA_VISIBLE_DEVICES=0,1 python cli_gt.py \
        --do_train \
        --output_dir ./out/webnlg/bart_few01/model \
        --train_file ./data/webnlg/train_01 \
        --train_file_unlabel ./data/webnlg/unlabel \
        --predict_file ./data/webnlg/val \
        --substitution_file ./data/counterfitted_neighbors.json \
        --model_path ./bart_model \
        --tokenizer_path ./bart_model \
        --curriculum [2,4,7] \
        --train_batch_size 32 \
        --train_batch_size_unlabel 32 \
        --predict_batch_size 64 \
        --predict_batch_size_unlabel 64 \
        --max_input_length 256 \
        --max_output_length 128 \
        --append_another_bos \
        --learning_rate 3e-5 \
        --num_train_epochs 20 \
        --num_train_epochs_unlabel 1 \
        --warmup_steps 80 \
        --warmup_steps_unlabel 400 \
        --eval_period 80 \
        --num_beams 5 \
        --struct_noise 0.4 \
        --semantic_noise 0.4 \
        --seed 42
